# Generated by Django 3.1.3 on 2021-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20210413_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
