# Generated by Django 3.1.3 on 2021-04-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_auto_20210416_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
            preserve_default=False,
        ),
    ]
