# Generated by Django 3.1.3 on 2021-04-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_payment_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
