# Generated by Django 3.1.3 on 2021-04-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_remove_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paied',
            field=models.BooleanField(default=False),
        ),
    ]
