# Generated by Django 3.1.3 on 2021-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_appointment_paied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paied',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
