# Generated by Django 3.1.3 on 2021-04-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_auto_20210425_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinics.appointment'),
            preserve_default=False,
        ),
    ]
