# Generated by Django 3.1.3 on 2021-05-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210524_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default_user_img.png', null=True, upload_to='media/users/profiles/images/'),
        ),
    ]
