# Generated by Django 3.1.3 on 2021-07-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210524_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDoctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndicate_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
